// <auto-generated />
using System;
using BEQuestionBank.Core.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BEQuestionBank.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250728054304_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BEQuestionBank.Domain.Models.AuditLog", b =>
                {
                    b.Property<long>("MaNhatKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MaNhatKy"));

                    b.Property<string>("DiaChiIP")
                        .HasColumnType("text");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<string>("GiaTriCu")
                        .HasColumnType("text");

                    b.Property<string>("GiaTriMoi")
                        .HasColumnType("text");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaBanGhi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("MaNguoiDung")
                        .HasColumnType("uuid");

                    b.Property<string>("TacNhanNguoiDung")
                        .HasColumnType("text");

                    b.Property<string>("TenBang")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenNguoiDung")
                        .HasColumnType("text");

                    b.Property<DateTime>("ThoiGianThucHien")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MaNhatKy");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("BEQuestionBank.Domain.Models.CauHoi", b =>
                {
                    b.Property<Guid>("MaCauHoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CLO")
                        .HasColumnType("integer");

                    b.Property<short>("CapDo")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("CauHoiChaMaCauHoi")
                        .HasColumnType("uuid");

                    b.Property<float?>("DoPhanCach")
                        .HasColumnType("real")
                        .HasColumnName("DoPhanCachCauHoi");

                    b.Property<bool>("HoanVi")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MaCauHoiCha")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MaPhan")
                        .HasColumnType("uuid");

                    b.Property<int>("MaSoCauHoi")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayCapNhap")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("NguoiTao")
                        .HasColumnType("uuid");

                    b.Property<string>("NoiDung")
                        .HasColumnType("text");

                    b.Property<int>("SoCauHoiCon")
                        .HasColumnType("integer");

                    b.Property<int?>("SoLanDung")
                        .HasColumnType("integer");

                    b.Property<int?>("SoLanDuocThi")
                        .HasColumnType("integer");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.Property<bool?>("XoaTam")
                        .HasColumnType("boolean");

                    b.HasKey("MaCauHoi");

                    b.HasIndex("CauHoiChaMaCauHoi");

                    b.HasIndex("MaPhan");

                    b.HasIndex("NguoiTao");

                    b.ToTable("CauHoi");
                });

            modelBuilder.Entity("BEQuestionBank.Domain.Models.CauTraLoi", b =>
                {
                    b.Property<Guid>("MaCauTraLoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("HoanVi")
                        .HasColumnType("boolean");

                    b.Property<bool>("LaDapAn")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MaCauHoi")
                        .HasColumnType("uuid");

                    b.Property<string>("NoiDung")
                        .HasColumnType("text");

                    b.Property<int>("ThuTu")
                        .HasColumnType("integer");

                    b.HasKey("MaCauTraLoi");

                    b.HasIndex("MaCauHoi");

                    b.ToTable("CauTraLoi");
                });

            modelBuilder.Entity("BEQuestionBank.Domain.Models.ChiTietDeThi", b =>
                {
                    b.Property<Guid>("MaDeThi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeThiMaDeThi")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MaCauHoi")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MaPhan")
                        .HasColumnType("uuid");

                    b.Property<int?>("ThuTu")
                        .HasColumnType("integer");

                    b.HasKey("MaDeThi");

                    b.HasIndex("DeThiMaDeThi");

                    b.HasIndex("MaCauHoi");

                    b.HasIndex("MaPhan");

                    b.ToTable("ChiTietDeThi");
                });

            modelBuilder.Entity("BEQuestionBank.Domain.Models.DeThi", b =>
                {
                    b.Property<Guid>("MaDeThi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("DaDuyet")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MaMonHoc")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("NgayCapNhap")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SoCauHoi")
                        .HasColumnType("integer");

                    b.Property<string>("TenDeThi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaDeThi");

                    b.HasIndex("MaMonHoc");

                    b.ToTable("DeThi");
                });

            modelBuilder.Entity("BEQuestionBank.Domain.Models.File", b =>
                {
                    b.Property<Guid>("MaFile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CauTraLoiMaCauTraLoi")
                        .HasColumnType("uuid");

                    b.Property<int?>("LoaiFile")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MaCauHoi")
                        .HasColumnType("uuid");

                    b.Property<string>("MaCauTraLoi")
                        .HasColumnType("text");

                    b.Property<string>("TenFile")
                        .HasColumnType("text");

                    b.HasKey("MaFile");

                    b.HasIndex("CauTraLoiMaCauTraLoi");

                    b.HasIndex("MaCauHoi");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("BEQuestionBank.Domain.Models.Khoa", b =>
                {
                    b.Property<Guid>("MaKhoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayCapNhap")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("XoaTam")
                        .HasColumnType("boolean")
                        .HasColumnName("XoaTamKhoa");

                    b.HasKey("MaKhoa");

                    b.ToTable("Khoa");
                });

            modelBuilder.Entity("BEQuestionBank.Domain.Models.MonHoc", b =>
                {
                    b.Property<Guid>("MaMonHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MaKhoa")
                        .HasColumnType("uuid");

                    b.Property<string>("MaSoMonHoc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayCapNhap")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SoTinChi")
                        .HasColumnType("integer");

                    b.Property<string>("TenMonHoc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("XoaTam")
                        .HasColumnType("boolean")
                        .HasColumnName("XoaTamMonHoc");

                    b.HasKey("MaMonHoc");

                    b.HasIndex("MaKhoa");

                    b.HasIndex("MaSoMonHoc")
                        .IsUnique();

                    b.ToTable("MonHoc");
                });

            modelBuilder.Entity("BEQuestionBank.Domain.Models.NguoiDung", b =>
                {
                    b.Property<Guid>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BiKhoa")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("KhoaMaKhoa")
                        .HasColumnType("uuid");

                    b.Property<string>("MaKhoa")
                        .HasColumnType("text");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayCapNhap")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VaiTro")
                        .HasColumnType("integer");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("KhoaMaKhoa");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("BEQuestionBank.Domain.Models.Phan", b =>
                {
                    b.Property<Guid>("MaPhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("LaCauHoiNhom")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MaMonHoc")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MaPhanCha")
                        .HasColumnType("uuid");

                    b.Property<int?>("MaSoPhan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayCapNhap")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NoiDung")
                        .HasColumnType("text");

                    b.Property<int>("SoLuongCauHoi")
                        .HasColumnType("integer");

                    b.Property<string>("TenPhan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ThuTu")
                        .HasColumnType("integer");

                    b.Property<bool?>("XoaTam")
                        .HasColumnType("boolean")
                        .HasColumnName("XoaTamPhan");

                    b.HasKey("MaPhan");

                    b.HasIndex("MaMonHoc");

                    b.ToTable("Phan");
                });

            modelBuilder.Entity("BEQuestionBank.Domain.Models.YeuCauRutTrich", b =>
                {
                    b.Property<Guid>("MaYeuCau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("DaXuLy")
                        .HasColumnType("boolean");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<Guid>("MaMonHoc")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MaNguoiDung")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("NgayXuLy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NgayYeuCau")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NoiDungRutTrich")
                        .HasColumnType("text");

                    b.HasKey("MaYeuCau");

                    b.HasIndex("MaMonHoc");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("YeuCauRutTrich");
                });

            modelBuilder.Entity("BEQuestionBank.Domain.Models.AuditLog", b =>
                {
                    b.HasOne("BEQuestionBank.Domain.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("BEQuestionBank.Domain.Models.CauHoi", b =>
                {
                    b.HasOne("BEQuestionBank.Domain.Models.CauHoi", "CauHoiCha")
                        .WithMany("CauHoiCons")
                        .HasForeignKey("CauHoiChaMaCauHoi");

                    b.HasOne("BEQuestionBank.Domain.Models.Phan", "Phan")
                        .WithMany()
                        .HasForeignKey("MaPhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BEQuestionBank.Domain.Models.NguoiDung", "NguoiDung")
                        .WithMany("CauHois")
                        .HasForeignKey("NguoiTao");

                    b.Navigation("CauHoiCha");

                    b.Navigation("NguoiDung");

                    b.Navigation("Phan");
                });

            modelBuilder.Entity("BEQuestionBank.Domain.Models.CauTraLoi", b =>
                {
                    b.HasOne("BEQuestionBank.Domain.Models.CauHoi", "CauHoi")
                        .WithMany("CauTraLois")
                        .HasForeignKey("MaCauHoi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CauHoi");
                });

            modelBuilder.Entity("BEQuestionBank.Domain.Models.ChiTietDeThi", b =>
                {
                    b.HasOne("BEQuestionBank.Domain.Models.DeThi", "DeThi")
                        .WithMany("ChiTietDeThis")
                        .HasForeignKey("DeThiMaDeThi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BEQuestionBank.Domain.Models.CauHoi", "CauHoi")
                        .WithMany()
                        .HasForeignKey("MaCauHoi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BEQuestionBank.Domain.Models.Phan", "Phan")
                        .WithMany()
                        .HasForeignKey("MaPhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CauHoi");

                    b.Navigation("DeThi");

                    b.Navigation("Phan");
                });

            modelBuilder.Entity("BEQuestionBank.Domain.Models.DeThi", b =>
                {
                    b.HasOne("BEQuestionBank.Domain.Models.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MaMonHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("BEQuestionBank.Domain.Models.File", b =>
                {
                    b.HasOne("BEQuestionBank.Domain.Models.CauTraLoi", "CauTraLoi")
                        .WithMany("FileDinhKems")
                        .HasForeignKey("CauTraLoiMaCauTraLoi");

                    b.HasOne("BEQuestionBank.Domain.Models.CauHoi", "CauHoi")
                        .WithMany("Files")
                        .HasForeignKey("MaCauHoi");

                    b.Navigation("CauHoi");

                    b.Navigation("CauTraLoi");
                });

            modelBuilder.Entity("BEQuestionBank.Domain.Models.MonHoc", b =>
                {
                    b.HasOne("BEQuestionBank.Domain.Models.Khoa", "Khoa")
                        .WithMany("DanhSachMonHoc")
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("BEQuestionBank.Domain.Models.NguoiDung", b =>
                {
                    b.HasOne("BEQuestionBank.Domain.Models.Khoa", "Khoa")
                        .WithMany()
                        .HasForeignKey("KhoaMaKhoa");

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("BEQuestionBank.Domain.Models.Phan", b =>
                {
                    b.HasOne("BEQuestionBank.Domain.Models.MonHoc", "MonHoc")
                        .WithMany("DanhSachPhan")
                        .HasForeignKey("MaMonHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("BEQuestionBank.Domain.Models.YeuCauRutTrich", b =>
                {
                    b.HasOne("BEQuestionBank.Domain.Models.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MaMonHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BEQuestionBank.Domain.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("BEQuestionBank.Domain.Models.CauHoi", b =>
                {
                    b.Navigation("CauHoiCons");

                    b.Navigation("CauTraLois");

                    b.Navigation("Files");
                });

            modelBuilder.Entity("BEQuestionBank.Domain.Models.CauTraLoi", b =>
                {
                    b.Navigation("FileDinhKems");
                });

            modelBuilder.Entity("BEQuestionBank.Domain.Models.DeThi", b =>
                {
                    b.Navigation("ChiTietDeThis");
                });

            modelBuilder.Entity("BEQuestionBank.Domain.Models.Khoa", b =>
                {
                    b.Navigation("DanhSachMonHoc");
                });

            modelBuilder.Entity("BEQuestionBank.Domain.Models.MonHoc", b =>
                {
                    b.Navigation("DanhSachPhan");
                });

            modelBuilder.Entity("BEQuestionBank.Domain.Models.NguoiDung", b =>
                {
                    b.Navigation("CauHois");
                });
#pragma warning restore 612, 618
        }
    }
}
